# Site settings
title: A blog about hoyoung Portfolio
description: Web Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jo Hoyoung
user_description: Web Developer
user_title: Web Developer
email: ho_9209@naver.com
twitter_username: none
github_username: 92hoy
gplus_username: hoy9209

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
